name: login_form
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  firebase_database: ^11.1.4
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  firebase_ui_database: ^1.5.0
  flutter_secure_storage: ^9.2.2
  multi_select_flutter: ^4.1.3
  flutter_riverpod: ^2.6.1
  firebase_messaging: ^15.2.2
  timeago: ^3.7.0
  flutter_svg: ^2.1.0
  syncfusion_flutter_charts: ^29.1.39
  syncfusion_flutter_pdfviewer: ^29.1.39
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.5.3
  animated_text_kit: ^4.2.3
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - images/home.png
    - images/splash.jpg
    - images/icon.png



flutter_native_splash:
  color: "#FFFFFF"
  image: images/splash.jpg
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true



  flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/icon.png"
    min_sdk_android: 21


