// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBID_ZdY68AKnkKU7SrILG5-4lAfMRcE_g',
    appId: '1:452095703370:web:9bdcb54ae2ad8b19f4e9b3',
    messagingSenderId: '452095703370',
    projectId: 'advocate-now',
    authDomain: 'advocate-now.firebaseapp.com',
    databaseURL: 'https://advocate-now-default-rtdb.firebaseio.com',
    storageBucket: 'advocate-now.firebasestorage.app',
    measurementId: 'G-MC28XSHMC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFzgYT50kPewojNztWaLzuZgDVPQIxAVA',
    appId: '1:20241724070:android:0262b64c5713f87b5afa67',
    messagingSenderId: '20241724070',
    projectId: 'legalmate-5f04c',
    storageBucket: 'legalmate-5f04c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAozBmDpYUkJTIMmxyRe96P6DwnuLaZKtg',
    appId: '1:20241724070:ios:dd2621980dd558e55afa67',
    messagingSenderId: '20241724070',
    projectId: 'legalmate-5f04c',
    storageBucket: 'legalmate-5f04c.firebasestorage.app',
    iosBundleId: 'com.example.loginForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-cF6vKQKBtsPdFS5DYPRWBQMwXranjbQ',
    appId: '1:452095703370:ios:14c93e19c888eb5bf4e9b3',
    messagingSenderId: '452095703370',
    projectId: 'advocate-now',
    storageBucket: 'advocate-now.appspot.com',
    iosBundleId: 'com.example.loginForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBID_ZdY68AKnkKU7SrILG5-4lAfMRcE_g',
    appId: '1:452095703370:web:4b602b64453e55d3f4e9b3',
    messagingSenderId: '452095703370',
    projectId: 'advocate-now',
    authDomain: 'advocate-now.firebaseapp.com',
    storageBucket: 'advocate-now.appspot.com',
    measurementId: 'G-DLZXV9W1HH',
  );
}